version: '3.0'

services:
  builder:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    entrypoint: uv run main.py
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
